export const homeObjOne = {
  id: "ensavoirplus",
  destination: "sophrologie",
  buttonRoute: false,
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "Qu'est ce que Le Meilleur de Soi ?",
  description:
    "Le meilleur de soi est une page Facebook créée en 2019 pendant ma première formation en sophrologie-relaxation-psychologie. Je poste des photos, des messages, des conseils sur le bien-être, la vision des choses, le ressenti des émotions.",
  description2:
    "Étant lassée de plus en plus par mon métier d’infirmière, j’ai décidé de m’orienter vers quelque chose qui me correspond plus à la personne que je suis actuellement. Le Meilleur de Soi est une entreprise où je mets mon savoir-faire et expérience au service des autres personnes qui ont envie de modifier ou supprimer des situations, ressentis ou autre événements gênant leur bien-être.",
  buttonLabel: "La sophrologie c'est quoi ?",
  imgStart: false,
  img: require("../../images/girl_against_tree.jpg").default,
  alt: "lemeilleurdesoi",
  dark: false,
  primary: false,
  darkText: true,
  photoAuthor: "Photo par Motoki Tonn sur Unsplash",
};

export const homeObjTwo = {
  id: "sophrologie",
  destination: "services",
  buttonRoute: false,
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "La sophrologie c'est quoi ?",
  description:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quam est, vulputate vitae viverra id, egestas vel nunc. Morbi euismod metus non erat convallis maximus. Vivamus leo elit, rutrum vitae mattis at, sagittis viverra felis. Sed et malesuada est. Curabitur iaculis nibh a diam porta scelerisque. Aliquam venenatis, nisi vel cursus vestibulum, magna ex placerat dolor, eget dapibus leo ante tincidunt turpis. Mauris ultrices massa turpis, aliquam viverra ligula imperdiet nec. Sed in libero sit amet lectus tempus ullamcorper eget ut sapien. Vivamus et nibh elementum, congue ante ut, rutrum leo.",
  description2: "",
  buttonLabel: "Voir les séances",
  imgStart: true,
  img: require("../../images/what_is_sophro.jpg").default,
  alt: "sophro",
  dark: false,
  primary: false,
  darkText: true,
  photoAuthor: "Photo par Elia Pellegrini sur Unsplash",
};

export const homeObjThree = {
  id: "A propos",
  destination: "/contact",
  buttonRoute: true,
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "Qui suis-je ?",
  description:
    "Je suis Sophie, infirmière depuis 30 ans. J’ai vécu il y a quelques années un burn-out et grâce à un accompagnement de qualité et des séances de sophrologie bihebdomadaires, je suis sortie de cette épreuve encore plus forte et plus apte à gérer les situations difficiles.",
  description2: " En 2019, je suis décidée à suivre la formation de praticien en sophro-relaxation en parallèle avec mon métier de nuit. J’ai adoré cette formation suivie à l’école Shen-Ti de l’Union. Puit de savoir et de techniques, de belles rencontres et la certitude d’aider les autres à atteindre le bien-être tel que je le perçois. Depuis, je me suis aussi formée au massage bien-être, le Amma assis, et je ne compte pas m’arrêter là. Au plaisir de vous rencontrer !",
  buttonLabel: "Me contacter",
  imgStart: true,
  img: require("../../images/portrait.jpg").default,
  alt: "portrait",
  dark: false,
  primary: false,
  darkText: true,
  photoAuthor: "",
};

export const contactObjOne = {
  id: "",
  destination: "",
  buttonRoute: true,
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "Où me trouver ?",
  description:
    "Les consultations se font à l'adresse suivante (hors séance de groupe extérieur)",
  description2: "33 chemin de Lespinasse 31140 Aucamville",
  buttonLabel: "Me contacter",
  imgStart: false,
  img: require("../../images/portrait.jpg").default,
  alt: "Mindfullness",
  dark: false,
  primary: false,
  darkText: true,
};
